### ISSUE TITLE
Are there plans to build this out?

### ISSUE THREAD

**Issue by jkjustjoshing** [react-bootstrap/reach-router-bootstrap#1]
I'm trying to use [Gatsby](https://www.gatsbyjs.org) (which uses [Reach Router](https://reach.tech/router)) with [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap). My understanding is that I will need reach-router-bootstrap to use the `<NavItem>` and `<Link>` components together.

Are there plans to build out this project? If I submitted a PR attempting an implementation based on how react-router-bootstrap is implemented, would that be appreciated?

**Comment by jquense** [comment]
happy to take something yeah. I was going to build out something but couldn't immediately think of a way to handle relative links, and kinda trailed off.

**Comment by jkjustjoshing** [comment]
I don't have much React and Reach experience, but I can give it a shot.

Any preference/requirements for build process? If not I'll use [create-react-library](https://github.com/transitive-bullshit/create-react-library).

**Comment by jquense** [comment]
We've got a babel-preset and eslint preset under the react-bootstrap scope we try and use for everything but beyond that go for whatever 👍

**Comment by jkjustjoshing** [comment]
I ended up opting not to use `react-bootstrap` in my project, so I didn't end up learning enough about its internals to build this out. Sorry!

**Comment by Anahkiasen** [comment]
@jquense Should this be reopened maybe? Would love to have this package exist
